### ISSUE TITLE
Annotate Methods with @MainThread and @NonNull

### ISSUE THREAD

**Issue by jpetitto** [pyricau/frenchtoast#4]
Do you think it would be worthwhile to include the `@MainThread` or `@NonNull` annotations when a method is required to be invoked on the main thread or a method's argument must be non-null, respectively? This may help developers catch errors at compile time that would result in an `Exception` to be thrown at runtime. Of course, this would require adding the Android support annotations library as a dependency.

**Comment by pyricau** [comment]
Why not. PR welcome!

**Comment by jpetitto** [comment]
Will do.

**Comment by pyricau** [comment]
Sorry for the delay. Thx for your contribution!
